import uuid
import json
from datetime import datetime
from app.core.logger import AgentLogger

class NotebookAgent:
    """
    Notebook Agent - Generates interactive notebooks and processes notebook instructions.
    """

    def __init__(self, session_id=None):
        self.session_id = session_id
        self.logger = AgentLogger("NotebookAgent")

    def _create_code_cell(self, source_lines):
        """Helper to create a standard code cell object."""
        # Ensure every line ends with a newline character for valid ipynb format
        formatted_source = [line if line.endswith('\n') else line + '\n' for line in source_lines]
        # Remove the newline from the very last line to be clean
        if formatted_source:
            formatted_source[-1] = formatted_source[-1].rstrip('\n')

        return {
            "id": str(uuid.uuid4()),
            "cell_type": "code",
            "source": formatted_source,
            "metadata": {},
            "outputs": []
        }

    def _create_markdown_cell(self, source_lines):
        """Helper to create a standard markdown cell object."""
        formatted_source = [line if line.endswith('\n') else line + '\n' for line in source_lines]
        return {
            "id": str(uuid.uuid4()),
            "cell_type": "markdown",
            "source": formatted_source,
            "metadata": {}
        }

    def generate_initial_notebook(self, filename, analysis_type="comprehensive_eda", dataframe_stats=None):
        """
        Generates the starting notebook structure.
        Accepts optional 'dataframe_stats' to generate smart, data-aware cells.
        """
        try:
            cells = []

            # --- Cell 1: Title & Introduction (Markdown) ---
            cells.append(self._create_markdown_cell([
                f"# {analysis_type.replace('_', ' ').title()}",
                f"**Target Dataset:** `{filename}`",
                "",
                "This notebook was auto-generated by AutoVizAI. Run the cells below to start analysis."
            ]))

            # --- Cell 2: Imports & Setup (Code) ---
            cells.append(self._create_code_cell([
                "import pandas as pd",
                "import numpy as np",
                "import plotly.express as px",
                "import plotly.io as pio",
                "",
                "# Set Plotly to render comfortably",
                "pio.templates.default = 'plotly_white'"
            ]))

            # --- Cell 3: Load Data (Code) ---
            cells.append(self._create_code_cell([
                "# Load the dataset",
                f"df = pd.read_csv('{filename}')",
                "print(f'Dataset loaded. Shape: {df.shape}')"
            ]))

            # --- Cell 4: Preview Data (Code) ---
            cells.append(self._create_code_cell([
                "# Display first 5 rows",
                "df.head()"
            ]))

            # --- Cell 5: Basic Info (Code) ---
            cells.append(self._create_code_cell([
                "# Check data types and missing values",
                "df.info()"
            ]))

            # --- SMART ENHANCEMENT: Data-Aware Visualizations ---
            # If we know the column names/types, let's add a smart chart immediately.
            if dataframe_stats:
                columns = dataframe_stats.get('columns', [])
                dtypes = dataframe_stats.get('dtypes', {})
                
                # Find the first numeric column for a distribution plot
                numeric_cols = [col for col in columns if 'int' in str(dtypes.get(col, '')).lower() or 'float' in str(dtypes.get(col, '')).lower()]
                
                if numeric_cols:
                    target_col = numeric_cols[0] # Pick the first numeric column
                    cells.append(self._create_markdown_cell([
                        "### Initial Distribution Check",
                        f"Visualizing the distribution of the `{target_col}` column."
                    ]))
                    cells.append(self._create_code_cell([
                        f"# Histogram for {target_col}",
                        f"fig = px.histogram(df, x='{target_col}', title='Distribution of {target_col}')",
                        "fig.show()"
                    ]))

            # --- Construct Final Notebook Object ---
            notebook_structure = {
                "metadata": {
                    "kernelspec": {
                        "display_name": "Python 3",
                        "language": "python",
                        "name": "python3"
                    },
                    "language_info": {
                        "codemirror_mode": {"name": "ipython", "version": 3},
                        "file_extension": ".py",
                        "mimetype": "text/x-python",
                        "name": "python",
                        "nbconvert_exporter": "python",
                        "pygments_lexer": "ipython3",
                        "version": "3.8.5"
                    },
                    "analysis_type": analysis_type,
                    "generated_at": datetime.now().isoformat()
                },
                "nbformat": 4,
                "nbformat_minor": 4,
                "cells": cells
            }

            return {
                "success": True,
                "data": {
                    "notebook": notebook_structure,
                    "summary": {
                        "title": f"Analysis of {filename}",
                        "cell_count": len(cells)
                    }
                }
            }

        except Exception as e:
            self.logger.log_error("notebook_generation_error", str(e))
            return {"success": False, "error": str(e)}